### ISSUE TITLE
Does not work with pgx 5.0.2

### ISSUE THREAD

**Issue by oschwald** [vgarvardt/pgx-google-uuid#15]
As reported in https://github.com/jackc/pgx/issues/1331, this package does not work with `pgx` 5.0.2. @jackc had this comment that may be helpful:

> It's hard to say just from the stack trace, but my guess is you are trying to encode a type that implements driver.Valuer by returning a value that itself implements driver.Valuer. This could cause infinite recursion because pgx calls Value() to get the type that it can encode. If this is the case, then that type appears to be violating the https://pkg.go.dev/database/sql/driver#Value contract.

**Comment by vgarvardt** [comment]
Yes, tests are failing at https://github.com/vgarvardt/pgx-google-uuid/pull/14 - will check it later today.

**Comment by jackc** [comment]
My fault. Seems to have been a tricky bug in pgx. I think it should work with current pgx master.

**Comment by oschwald** [comment]
I am closing this as it was fixed in `pgx`.
